config/routes.rb
Merseri::Application.routes.draw do

  resources :items do
    resources :tags
  end

  resources :actings
  
  resources :users do
    member do
      get :mers
      get :activities
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :mers do
    resources :tags
    resources :comments
  end
  
  resources :mers do
    member do
      put :vote_up
      put :vote_down
      get :add_collection
      get :remove_this_collection
    end
  end
  
  resources :activities do
    member do
      get :on_frontpage
    end
  end
   
  root  'welcome#welcome'
  match '/signup',                    to: 'users#new',                 via: 'get'
  match '/signin',                    to: 'sessions#new',              via: 'get'
  match '/signout',                   to: 'sessions#destroy',          via: 'delete'
  match '/search/mers',               to: 'mers#search',               via: 'get', as: 'search_mers'
  match '/search/items',              to: 'items#search',              via: 'get', as: 'search_items'
  
  match '/printing/print_collection', to: 'printing#print_collection', via: 'get', as: 'print_collection' 
  match '/printing/print_all',        to: 'printing#print_all',        via: 'get', as: 'print_all'
  match '/printing/collection_email', to: 'printing#collection_email', via: 'get', as: 'collection_email'
  match '/printing/remove_collection',to: 'printing#remove_collection',via: 'get', as: 'remove_collection'
 
  match '/action',                    to: 'activities#action',         via: 'get', as: 'action'
  match '/history',                   to: 'activities#history',        via: 'get', as: 'history'
  match '/on_acting',                 to: 'actings#on_acting',         via: 'get', as: 'on_acting'
 
  match '/help',                      to: 'welcome#help',              via: 'get', as: 'help'
  match '/about',                     to: 'welcome#about',             via: 'get'
  match '/contact',                   to: 'welcome#contact',           via: 'get'
  match '/newuser',                   to: 'welcome#newuser',           via: 'get', as: 'newuser'
  match '/welcome',                   to: 'welcome#welcome',           via: 'get', as: 'welcome'

  match '/notes_page',                     to: 'mers#notes_page',             via: 'get', as: 'notes_page'
  match '/timeline_page',                  to: 'timelines#timeline_page',          via: 'get', as: 'timeline_page'
  match '/inventory_page',                 to: 'items#inventory_page',         via: 'get', as: 'inventory_page'
  
  match '/users/:id/edit/on',   to: 'users#admin_on',    via: 'get', as: 'admin_on'
  match '/users/:id/edit/off',  to: 'users#admin_off',   via: 'get', as: 'admin_off'
  
  get '/mers/tags/:tag',    to: 'mers#index',   as: :tag_mers
  get 'items/tags/:tag',    to: 'items#index',   as: :tag_items

  
  
  
  
  namespace :api, :defaults => {format: :json} do
    namespace :v1 do
      /devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end/
      get 'tasks' => 'tasks#index', as: 'tasks'
    end
  end
  
  
  

  

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  layout 'welcome_layout'
  
  
  def sign_in
    if !current_user
      redirect_to signin_path
    end
  end
  
  def help
  end
  
  def about
  end
  
  def contact
  end 
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/about.html.erb
<% provide(:title, 'About') %>
<div class="container">
<h1>About</h1>
  All work here is still under development. All data, private or public, can be destroyed without a further notice. If you like to support development please follow the link below.
	<br  /> 
	<br  />
	<%= link_to "Donation", 'https://www.merseri.com/arinblog/', method: :get, target: "_blank" %>
</div>

app/views/welcome/contact.html.erb
<% provide(:title, 'Contact') %>
<div class="container">
<h1>Contact</h1>
<p id="demo">
	Please send all your comments to Ari
</p>
<button type="button" onclick="myFunction()">Click Me!</button>

</div>

app/views/welcome/inventory.html.erb
<div class="container">
  <h1>Welcome to INVENTORY</h1>
  <br  />
	<ul>
		<li>household items</li>
		<li>household maintenance</li>
		<li>insurances</li>
		<li>car service</li>
		<li>sw licences nos</li>
		<li>reminders</li>
		<li>electronics serie nos</li>
		<li>art</li>
		<li>instruments</li>
	</ul>
 <br  />
 <%= link_to "back to welcome", welcome_path, class: "btn btn-lg btn-success" %>
 <br  />
 <br  />
 <%= link_to "back to welcome", welcome_path, class: "btn btn-lg btn-primary" %>
 <br  />
</div>

app/views/welcome/netcommunity.html.erb
<div class="container">
  <h1>Welcome to NETCOMMUNITY</h1>
  </br>
  <%= link_to "back to welcome", welcome_path, class: "btn btn-large btn-primary" %>
  </br>
  </br>
  </br>
</div>

app/views/welcome/notes.html.erb
<div class="container">
  <h1>Welcome to NOTES</h1>
  <br  />
	<%= link_to "New note", new_mer_path, class: "btn btn-lg btn-success" %>
	<br  />
	<br  />
	<%= link_to "back to welcome", welcome_path, class: "btn btn-lg btn-primary" %>
</div>

app/views/welcome/reminder.html.erb
<div class="container">
  <h1>Welcome to REMINDER</h1>
  <br  />
	<div class="row">
    <div class="col-md-6">
			<div id='calendar'></div>
		</div>	
	</div>
	<ul>
		<li>long term planning</li>
		<li>important days</li>
		<li>dreams, lifelong intentions</li>
		<li>timeline</li>
		<li>follow up</li>
		<li>reminders</li>
		<li>planned and executed activities</li>
	</ul>
	<br  />
	<%= link_to "Calender", calenders_path, method: :get, class: "btn btn-lg btn-success" %>
  <br  />
  <br  />
  <%= link_to "back to welcome", welcome_path, class: "btn btn-lg btn-primary" %>
  <br  />

</div>

app/views/welcome/timeline.html.erb
<div class="container">
  <h1>Welcome to TIMELINE</h1>
  <br  />
	<div class="row">
    <div class="col-md-6">
			<div id='calendar'></div>
		</div>	
	</div>
	<ul>
		<li>long term planning</li>
		<li>important days</li>
		<li>dreams, lifelong intentions</li>
		<li>timeline</li>
		<li>follow up</li>
		<li>reminders</li>
		<li>planned and executed activities</li>
	</ul>
	<br  />
  <br  />
  <br  />
  <%= link_to "back to welcome", welcome_path, class: "btn btn-lg btn-primary" %>
  <br  />

</div>

app/views/welcome/welcome.html.erb
<% provide(:title, 'Welcome') %>
<div class="container">
	<br  />
	<div class="row">
    <div class="col-sm-2">
			<%= button_to "ACTION", action_path, method: :get, class: "btn btn-primary btn-custom" %>
		</div>
		<div class="col-sm-2">
			<%= button_to "NOTES", new_mer_path, method: :get, class: "btn btn-success btn-custom" %>
		</div>
	</div>
	<div class="row">
    <div class="col-sm-2">
			<%= button_to "TIMELINE", timeline_page_path, method: :get, class: "btn btn-warning btn-custom" %>
		</div>
		<div class="col-sm-2">
			<%= button_to "INVENTORY", inventory_page_path, method: :get, class: "btn btn-danger btn-custom" %>
	  </div>
	</div>
</div>