config/routes.rb
Merseri::Application.routes.draw do

  resources :items do
    resources :tags
  end

  resources :actings
  
  resources :users do
    member do
      get :mers
      get :activities
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :mers do
    resources :tags
    resources :comments
  end
  
  resources :mers do
    member do
      put :vote_up
      put :vote_down
      get :add_collection
      get :remove_this_collection
    end
  end
  
  resources :activities do
    member do
      get :on_frontpage
    end
  end
   
  root  'welcome#welcome'
  match '/signup',                    to: 'users#new',                 via: 'get'
  match '/signin',                    to: 'sessions#new',              via: 'get'
  match '/signout',                   to: 'sessions#destroy',          via: 'delete'
  match '/search/mers',               to: 'mers#search',               via: 'get', as: 'search_mers'
  match '/search/items',              to: 'items#search',              via: 'get', as: 'search_items'
  
  match '/printing/print_collection', to: 'printing#print_collection', via: 'get', as: 'print_collection' 
  match '/printing/print_all',        to: 'printing#print_all',        via: 'get', as: 'print_all'
  match '/printing/collection_email', to: 'printing#collection_email', via: 'get', as: 'collection_email'
  match '/printing/remove_collection',to: 'printing#remove_collection',via: 'get', as: 'remove_collection'
 
  match '/action',                    to: 'activities#action',         via: 'get', as: 'action'
  match '/history',                   to: 'activities#history',        via: 'get', as: 'history'
  match '/on_acting',                 to: 'actings#on_acting',         via: 'get', as: 'on_acting'
 
  match '/help',                      to: 'welcome#help',              via: 'get', as: 'help'
  match '/about',                     to: 'welcome#about',             via: 'get'
  match '/contact',                   to: 'welcome#contact',           via: 'get'
  match '/newuser',                   to: 'welcome#newuser',           via: 'get', as: 'newuser'
  match '/welcome',                   to: 'welcome#welcome',           via: 'get', as: 'welcome'

  match '/notes_page',                     to: 'mers#notes_page',             via: 'get', as: 'notes_page'
  match '/timeline_page',                  to: 'timelines#timeline_page',          via: 'get', as: 'timeline_page'
  match '/inventory_page',                 to: 'items#inventory_page',         via: 'get', as: 'inventory_page'
  
  match '/users/:id/edit/on',   to: 'users#admin_on',    via: 'get', as: 'admin_on'
  match '/users/:id/edit/off',  to: 'users#admin_off',   via: 'get', as: 'admin_off'
  
  get '/mers/tags/:tag',    to: 'mers#index',   as: :tag_mers
  get 'items/tags/:tag',    to: 'items#index',   as: :tag_items

  
  
  
  
  namespace :api, :defaults => {format: :json} do
    namespace :v1 do
      /devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end/
      get 'tasks' => 'tasks#index', as: 'tasks'
    end
  end
  
  
  

  

end

app/controllers/printing_controller.rb
class PrintingController < ApplicationController
  
  layout 'notes_layout'
  before_action :sign_in_check
    
  def print_selected
    @mer = current_user
  end
    
  def print_all
    @mers = current_user.mers
  end
  
  def remove_collection
    session[:print] = Array.new
  end
  
  def print_collection
    if !session[:print]
      redirect_to remove_collection_path
    else
      @user = current_user
      @mers = Mer.order('vote DESC').find(session[:print])
    end
  end
  
  def collection_email
    @user = current_user
    @mers = Mer.order('vote DESC').find(session[:print])
    UserMailer.collection_email(@mers, @user).deliver
  end
end

app/helpers/printing_helper.rb
module PrintingHelper
end

app/views/printing/addCollection.html.erb
<% provide(:title, 'Add collection') %>
<h1>Printing#addCollection</h1>
<h2>Idea <%= @collection.id %> is added to collection</h2>


<strong>Idea:</strong>
<br  />
<%= @collection.title %>

app/views/printing/add_collection.html.erb
<% provide(:title, 'Add collection') %>
<div class="container">
<h3>"<%= @mer_added.text %>" <br /><br />is added to collection</h3>
<br  />
<br  />
<%= link_to 'Back', :back %>
</div>

app/views/printing/collection_email.html.erb
<% provide(:title, 'email') %>
<div class="container">
	<br  />
  <h3>Collection email sent to <%= @user.email %></h3>
</div>

app/views/printing/printAll.html.erb
<h1>Printing#printAll</h1>
<h2>Show all ideas</h2>


<div="mers">
<hr />
<% @mers.each do |mer| %>
    <%= link_to mer.title, mer %>
    <%= simple_format(mer.text) %>
<hr />
	
<% end %>

</div>

app/views/printing/printCollection.html.erb
<% provide(:title, 'Print all') %>
<h1>Printing#printCollection</h1>
<h3>This is a link to all ideas of current user</h3>

<%= link_to "All ideas", mers_path %>

app/views/printing/printSelected.html.erb
<% provide(:title, 'Selected') %>

<h1>Printing#printSelected</h1>
<h3>To be selected for collection</h3>
<p>
  <strong>Idea:</strong>
  <br />
  <%= @mer.title %>
</p>
 
<p>
  <strong>Notes:</strong>
  <br />
  <%= @mer.text %>
</p>

app/views/printing/print_all.html.erb
<h1>Printing#printAll</h1>
<h2>Show all notes</h2>
<div="mers">
<hr />
<% @mers.each do |mer| %>
    <%= link_to mer.title, mer %>
    <%= simple_format(mer.text) %>
<hr />	
<% end %>
</div>

app/views/printing/print_collection.html.erb
<% provide(:title, 'Print all') %>
<div class="container">
	<h1>Notes in this collection</h1>
	<br  />
  <% if @mers.empty? %>
	  <h2>Collection is empty.</h2>
  <% else %>

	  <% @mers.each do |mer| %>
		  <% @mer = mer %>
			<%= link_to 'remove from collection', remove_this_collection_mer_path(mer), class: "btn btn-sm btn-primary"  %>
		  <%= render 'mers/show_short' %> 
		<% end %>
		<ul>
		  <li><h3><%= link_to 'Empty collection', remove_collection_path  %></h3></li>
		  <li><h3><%= link_to 'Email collection', collection_email_path  %></h3></li>
	  </ul>
		<br  />
  <% end %>
</div>

app/views/printing/remove_collection.html.erb
<% provide(:title, 'removed') %>
<div class="container">
<h2>All ideas are now removed from collection</h2>
</div>