config/routes.rb
Merseri::Application.routes.draw do

  resources :items do
    resources :tags
  end

  resources :actings
  
  resources :users do
    member do
      get :mers
      get :activities
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :mers do
    resources :tags
    resources :comments
  end
  
  resources :mers do
    member do
      put :vote_up
      put :vote_down
      get :add_collection
      get :remove_this_collection
    end
  end
  
  resources :activities do
    member do
      get :on_frontpage
    end
  end
   
  root  'welcome#welcome'
  match '/signup',                    to: 'users#new',                 via: 'get'
  match '/signin',                    to: 'sessions#new',              via: 'get'
  match '/signout',                   to: 'sessions#destroy',          via: 'delete'
  match '/search/mers',               to: 'mers#search',               via: 'get', as: 'search_mers'
  match '/search/items',              to: 'items#search',              via: 'get', as: 'search_items'
  
  match '/printing/print_collection', to: 'printing#print_collection', via: 'get', as: 'print_collection' 
  match '/printing/print_all',        to: 'printing#print_all',        via: 'get', as: 'print_all'
  match '/printing/collection_email', to: 'printing#collection_email', via: 'get', as: 'collection_email'
  match '/printing/remove_collection',to: 'printing#remove_collection',via: 'get', as: 'remove_collection'
 
  match '/action',                    to: 'activities#action',         via: 'get', as: 'action'
  match '/history',                   to: 'activities#history',        via: 'get', as: 'history'
  match '/on_acting',                 to: 'actings#on_acting',         via: 'get', as: 'on_acting'
 
  match '/help',                      to: 'welcome#help',              via: 'get', as: 'help'
  match '/about',                     to: 'welcome#about',             via: 'get'
  match '/contact',                   to: 'welcome#contact',           via: 'get'
  match '/newuser',                   to: 'welcome#newuser',           via: 'get', as: 'newuser'
  match '/welcome',                   to: 'welcome#welcome',           via: 'get', as: 'welcome'

  match '/notes_page',                     to: 'mers#notes_page',             via: 'get', as: 'notes_page'
  match '/timeline_page',                  to: 'timelines#timeline_page',          via: 'get', as: 'timeline_page'
  match '/inventory_page',                 to: 'items#inventory_page',         via: 'get', as: 'inventory_page'
  
  match '/users/:id/edit/on',   to: 'users#admin_on',    via: 'get', as: 'admin_on'
  match '/users/:id/edit/off',  to: 'users#admin_off',   via: 'get', as: 'admin_off'
  
  get '/mers/tags/:tag',    to: 'mers#index',   as: :tag_mers
  get 'items/tags/:tag',    to: 'items#index',   as: :tag_items

  
  
  
  
  namespace :api, :defaults => {format: :json} do
    namespace :v1 do
      /devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end/
      get 'tasks' => 'tasks#index', as: 'tasks'
    end
  end
  
  
  

  

end

app/models/item.rb
class Item < ActiveRecord::Base

  acts_as_taggable  
  belongs_to :user
  
  before_save { self.name = name.capitalize }
  
  validates :name, :presence => {:message => 'Item name cannot be blank'}, :length => { :minimum => 3 }

  def self.search(query)
   # where(:title, query) -> This would return an exact match of the query
   where("name like ?", "%#{query}%") 
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  layout 'items_layout'
  before_action :sign_in_check
  
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index    
    
    if params[:search] && current_user.admin?
      @items = Item.all.search(params[:search]).order('name DESC')
    elsif params[:tag] && current_user.admin?
      @items = Item.all.tagged_with(params[:tag])
    elsif params[:search]
      @items = current_user.items.search(params[:search]).order('name DESC')
    elsif params[:tag]
      @items = current_user.items.tagged_with(params[:tag])
    elsif
      @items = current_user.items
      @reminder_items = Item.where("user_id = ? AND alarm = ? ", current_user.id, true)
    end
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    @user = User.find(@item.user_id)
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end
  
  def search
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:name, :description, :user_id, :set_time, :alarm, :tag_list, :search)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_for(@item, :html => { class: "form-mer"}) do |f| %>
  <% if @item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>
      <ul>
      <% @item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
<% end %>
<div class="panel panel-primary panel-form">
		<div class="panel-body panel-primary">
		    <%= f.label :"name:" %><br  />
		    <%= f.text_field :name, class: "form-control" %>
				<br  />
		    <%= f.label :"description:" %><br  />
		    <%= f.text_area :description, class: "form-control" %>
				<br  />
		    <%= f.hidden_field :user_id, value: current_user.id, class: "form-control" %>
				<br  />
		   <%= f.label :"Tag:" %><br  />
		   <%= f.text_field :tag_list, class: "form-control" %>
			 <br  />
		    <%= f.label :"set reminder time:" %><br  />
				<%= f.text_field :set_time, id: "datepicker" %>

			<br  />
			<label class="checkbox pull-left">
				<%= f.label "Alarm?" %>			
        <%= f.check_box :alarm, class: "form-control" %>
      </label>
			<br  />
			<br  />
			<br  />
			<br  />
		  <%= f.submit "Save", class: "btn btn-lg btn-primary" %>
			<span class="clearfix"></span>
   <% end %>
	</div>
</div>

app/views/items/_search.html.erb
<div class="panel panel-primary panel-form">
		<div class="panel-body panel-primary">
			<%= form_tag(items_path, :method => "get", :html => { class: "form-search"}) do %>
			  <%= text_field_tag :search, params[:search], placeholder: "Search for inventory items...", class: "form-control" %>
			  <br  />
				<%= submit_tag "Search", :name => nil, class: "btn btn-lg btn-primary btn-block" %>
				<br  />
			<% end %>
			<div>
			  <%= link_to "New item", new_item_path, method: :get, class: "btn btn-lg btn-success" %>
			</div %>
			<br  />
			<div id="tag_cloud">
			  <%= render 'items/tagcloud' %>
			</div>
		</div>
</div>

app/views/items/_show_item.html.erb
<div class="panel panel-primary">
	<div class="panel-heading">by <%= @user.name %>, created on <%= @item.created_at.localtime.to_formatted_s(:rfc822) %></div>
  <div class="panel-body panel-primary">
		Name:
    <div class="well">
			<%= @item.name %>
		</div>
		Descpription:
    <div class="well">
			<%= @item.description %>
		</div>
		Tags:
    <div class="well">
			<%= raw @item.tag_list.map { |t| link_to t, tag_items_path(t) }.join(', ') %>
		</div>
  </div>	
  <div class="panel-footer">
						<%= link_to 'edit', edit_item_path(@item), method: :get %>
	</div>
</div>
	

app/views/items/_tagcloud.html.erb
<% tag_cloud (current_user.admin ?  Item.tag_counts : current_user.items.tag_counts) , %w{s m l} do |tag, css_class| %>
  <%= link_to tag.name, tag_items_path(tag.name), class: css_class %>
<% end %>

app/views/items/edit.html.erb
<div class="container">
	<h1>Editing item</h1>

  <%= render 'form' %>

  <%= link_to 'Show', @item %> |
  <%= link_to 'Back', items_path %>
</div>

app/views/items/index.html.erb
<% provide(:title, 'Notes') %>
<div class="container">
  <br  />
	<div class="container">
		<%= render 'items/search' %>
		<br  />
	  <% @items.each do |i| %>
		<% @item = i %>
		<% @user = User.find(i.user_id) %>
		<%= render 'show_item' %>			  
	  <% end %>
  </div>
</div>


<div class="container">
<h1>Listing items</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>|Description</th>
      <th>|User</th>
      <th>|Set time</th>
      <th>|Alarm</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.name %></td>
        <td><%= item.description %></td>
        <td><%= User.find(item.user_id).name %></td>
        <td><%= item.set_time %></td>
        <td><%= item.alarm %></td>
        <td><%= link_to '|Show', item %></td>
        <td><%= link_to '|Edit', edit_item_path(item) %></td>
        <td><%= link_to '|Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>
</div>

app/views/items/inventory_page.html.erb
<div class="container">
  <h1>Welcome to INVENTORY</h1>
  <br  />
	<ul>
		<li>household items</li>
		<li>household maintenance</li>
		<li>insurances</li>
		<li>car service</li>
		<li>sw licences nos</li>
		<li>reminders</li>
		<li>electronics serie nos</li>
		<li>art</li>
		<li>instruments</li>
	</ul>	
</div>

app/views/items/new.html.erb
<div class="container">
  <h1>New item</h1>
  <%= render 'form' %>
</div>

app/views/items/search.html.erb
<div class="container">
<% provide(:title, 'Search') %>
<div class="container">
  <%= render 'search' %>
</div>
</div>

app/views/items/show.html.erb
<% provide(:title, 'Item') %>
<div class="container">
  <h1>Inventory item:</h1>
  <%= render 'show_item' %>	
</div>