config/routes.rb
Merseri::Application.routes.draw do

  resources :items do
    resources :tags
  end

  resources :actings
  
  resources :users do
    member do
      get :mers
      get :activities
    end
  end
  
  resources :sessions, only: [:new, :create, :destroy]
  
  resources :mers do
    resources :tags
    resources :comments
  end
  
  resources :mers do
    member do
      put :vote_up
      put :vote_down
      get :add_collection
      get :remove_this_collection
    end
  end
  
  resources :activities do
    member do
      get :on_frontpage
    end
  end
   
  root  'welcome#welcome'
  match '/signup',                    to: 'users#new',                 via: 'get'
  match '/signin',                    to: 'sessions#new',              via: 'get'
  match '/signout',                   to: 'sessions#destroy',          via: 'delete'
  match '/search/mers',               to: 'mers#search',               via: 'get', as: 'search_mers'
  match '/search/items',              to: 'items#search',              via: 'get', as: 'search_items'
  
  match '/printing/print_collection', to: 'printing#print_collection', via: 'get', as: 'print_collection' 
  match '/printing/print_all',        to: 'printing#print_all',        via: 'get', as: 'print_all'
  match '/printing/collection_email', to: 'printing#collection_email', via: 'get', as: 'collection_email'
  match '/printing/remove_collection',to: 'printing#remove_collection',via: 'get', as: 'remove_collection'
 
  match '/action',                    to: 'activities#action',         via: 'get', as: 'action'
  match '/history',                   to: 'activities#history',        via: 'get', as: 'history'
  match '/on_acting',                 to: 'actings#on_acting',         via: 'get', as: 'on_acting'
 
  match '/help',                      to: 'welcome#help',              via: 'get', as: 'help'
  match '/about',                     to: 'welcome#about',             via: 'get'
  match '/contact',                   to: 'welcome#contact',           via: 'get'
  match '/newuser',                   to: 'welcome#newuser',           via: 'get', as: 'newuser'
  match '/welcome',                   to: 'welcome#welcome',           via: 'get', as: 'welcome'

  match '/notes_page',                     to: 'mers#notes_page',             via: 'get', as: 'notes_page'
  match '/timeline_page',                  to: 'timelines#timeline_page',          via: 'get', as: 'timeline_page'
  match '/inventory_page',                 to: 'items#inventory_page',         via: 'get', as: 'inventory_page'
  
  match '/users/:id/edit/on',   to: 'users#admin_on',    via: 'get', as: 'admin_on'
  match '/users/:id/edit/off',  to: 'users#admin_off',   via: 'get', as: 'admin_off'
  
  get '/mers/tags/:tag',    to: 'mers#index',   as: :tag_mers
  get 'items/tags/:tag',    to: 'items#index',   as: :tag_items

  
  
  
  
  namespace :api, :defaults => {format: :json} do
    namespace :v1 do
      /devise_scope :user do
        post 'registrations' => 'registrations#create', :as => 'register'
        post 'sessions' => 'sessions#create', :as => 'login'
        delete 'sessions' => 'sessions#destroy', :as => 'logout'
      end/
      get 'tasks' => 'tasks#index', as: 'tasks'
    end
  end
  
  
  

  

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user
  has_many :actings, dependent: :destroy
  
  before_save { self.name = name.capitalize }
  
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController


  layout 'actions_layout'
  before_action :sign_in_check

  def new
    @activity = Activity.new
  end

  def edit
     @activity = Activity.find(params[:id])
  end

  def create
    @activity = current_user.activities.new(activity_params)
    if @activity.save
      redirect_to action_path, notice: 'Activity was successfully created.'
    else
      render action: 'new'
    end
  end

  def index
    @all_activities = Activity.where("user_id = ?", current_user.id)
  end

  def show
    @activity = Activity.find(params[:id])
  
    
  end

  def update
    @activity = Activity.find(params[:id])
      if @activity.update(activity_params)
        redirect_to activities_path, notice: 'Activity was successfully updated.'
      else
        render action: 'edit'
      end
  end

  def destroy
    @activity = Activity.find(params[:id])
    @activity.destroy
    redirect_to activities_path
  end

  def on_frontpage  
    @activity = Activity.find(params[:id])
    if !@activity.active
      if @activity.update_attribute :active, true
        flash[:notice] = "Activity updated"
        redirect_to action_path
      end
    else
      if @activity.update_attribute :active, false
        flash[:notice] = "Activity updated"
      end
      redirect_to activities_path
    end
    @my_activities = current_user.activities.all
  end
  
  def action
    @active_activities = Activity.where("user_id = ? AND active = ?", current_user.id, true)
  end
  
  def history
    @actings_cu = Acting.where("user_id = ?", current_user.id).order('start DESC')
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    def activity_params
      params.require(:activity).permit(:name, :user_id, :active)
    end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<br  />
<div class="panel panel-primary panel-form">
		<div class="panel-body panel-primary">
			<%= form_for(@activity, :html => { class: "form-mer"}) do |a| %>
			   
			   <%= a.label :name %><br  />
			   <%= a.text_field :name, class: "form-control" %><br  />
				 <br  />
				 <div><%= a.radio_button :active, true , :checked => true , :value => true %>
					 <%= label :active, "Show on the frontpage" %>				       
				 </div>
			   <br  />
				 <div><%= a.radio_button :active, false, :value => false %>
					 <%= label :active, "Don't show on the frontpage"%>				        
				 </div>
				 <br  />
			   <%= a.submit "Save", class: "btn btn-lg btn-primary btn-block" %>
				 <span class="clearfix"></span>
			<% end %>
	</div>
</div>

app/views/activities/action.html.erb
<div class="container">	
	
  <h1>Select activity</h1>
	<br  />
	<div class="row"> 
		<% @active_activities.each do |m| %> 
		<div class="col-md-4">
			<%= link_to new_acting_path(activity_id: m.id), class: "btn btn-lg btn-warning btn-block" do %>
			  <%= m.name %>
			  <% m.actings.all.each do |a| %>
			    <% if a.start == a.stop %>
			      ongoing...
			    <% end %>
		  	<% end %>
			<% end %>
		  <br  />
		</div>
	  <% end %>
	</div>		
</div>

app/views/activities/edit.html.erb
<div class="container">
	<h1>Editing activity</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @activity %> |
	<%= link_to 'Back', activities_path %>
</div>

app/views/activities/history.html.erb
<div class="container">
	<br  />
	<h2><%= current_user.name %> all activities</h2>
	<table>
	  <thead>
	    <tr>
	      <th>Activity....................</th>
	      <th>started...........</th>
	      <th>stopped...........</th>
	      <th></th>
	      <th></th>
				<th></th>
	    </tr>
	  </thead>

	  <tbody>
	    <% @actings_cu.each do |a| %>
	      <tr>
	        <td><%= Activity.find(a.activity_id).name %></td>
	        <td><%= a.start.to_formatted_s(:short) %></td>
					<td><%= a.stop.to_formatted_s(:short) %></td>
	        <td><%= link_to 'Show', acting_path(a) %></td>
	        <td> |<%= link_to 'Edit', edit_acting_path(a) %></td>
	        <td> |<%= link_to 'Destroy', acting_path(a), method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>


</div>

app/views/activities/index.html.erb
<div class="container">
	<br  />
	<% if @all_activities.empty? %>
		<div class="row">  
			<div class="col-md-6">
				<%= link_to "new activity", new_activity_path, class: "btn btn-lg btn-primary btn-block" %>		
	    </div>
		</div>
	<% else %>
	  <% @all_activities.each do |a| %>
		  <% @user = User.find(a.user_id) %>
	    <div class="panel panel-primary">
		    <div class="panel-heading"></div>
	      <div class="panel-body panel-primary">
	        <div class="well">
			      <%= a.name %>
			    </div>
	      <div class="panel-footer">			
				    <% if !a.active %>
						  <%= button_to "Show on the frontpage", on_frontpage_activity_path(a), method: :get, class: "btn btn-sm btn-success" %>
						<% else %>
						  <%= button_to "Don't show on the frontpage", on_frontpage_activity_path(a), method: :get, class: "btn btn-sm btn-danger" %>						 
						<% end %>			
        <br  />
				<%= link_to 'Delete', activity_path(a), method: :delete, data: { Confirm: 'Are you sure?' } %>
				| <%= link_to "Edit", edit_activity_path(a) %>
	    </div>
	  </div>
	  </div>
		<% end %>
  <% end %>	
</div>

app/views/activities/my_act.html.erb
<div class="container">
	<h3>"<%= @activity.name %>" added to the front page</h3>
	<br  />
	My all activities are:
	<ul>
	<% @my_activities.each do |m| %>
	<li>
	<%= m.name %> | <%= link_to 'delete', activity_path(m), method: :delete, data: { Confirm: 'Are you sure?' } %>
	</li>
	<% end %>
	</ul>
	<br  />
		<%= link_to 'Action', action_path %> |
	<%= link_to 'Show', @activity %> |
	<%= link_to 'Back', activities_path %>
</div>

app/views/activities/new.html.erb
<div class="container">
<h1>New activity</h1>

<%= render 'form' %>

</div>

app/views/activities/show.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @activity.name %>
</p>

<p>
  <strong>User:</strong>
  <%= @activity.user_id %>
</p>


<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Delete', activity_path(@activity), method: :delete, data: { Confirm: 'Are you sure?' } %> |
<%= link_to 'Back', activities_path %>
</div>

app/views/activities/time.html.erb
<div class="container">	
	
  <h1>Welcome to TIME</h1>
	<div class="row">  
		<div class="col-md-6">
			<%= link_to "new activity", new_activity_path, class: "btn btn-lg btn-primary btn-block" %>		
    </div>
		<div class="col-md-6">
      <%= link_to "Show activities", activities_path, class: "btn btn-lg btn-primary btn-block" %><br  />
	  </div>
  </div>
	<br  />
	<div class="row"> 
		<% @my_activities.each do |my_activity| %> 
		<div class="col-md-4">
			<%= link_to my_activity.name, new_acting_path(activity_id: my_activity.id), class: "btn btn-lg btn-warning btn-block" %>
			<br  />
		</div>
		<% end %>
	</div>
	<br  />
	<div class="row">  
		<div class="col-md-12">
			<%= link_to "history", history_path, class: "btn btn-lg btn-success btn-block" %>
			<%= link_to "back to welcome", welcome_path, class: "btn btn-lg btn-success btn-block" %>
		</div>
	</div>		
</div>